Traceback (most recent call last):
  File "/hdd1/aidml/sjwi/ML2024/train.py", line 90, in <module>
    pred = model(x)
  File "/home/aidml/miniconda3/envs/ml2024/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/aidml/miniconda3/envs/ml2024/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/hdd1/aidml/sjwi/ML2024/src/models/VanillaCNN.py", line 39, in forward
    x = self.convs(x)
  File "/hdd1/aidml/sjwi/ML2024/src/models/VanillaCNN.py", line 30, in convs
    x = self.pool(F.relu(self.conv1(x)))
  File "/home/aidml/miniconda3/envs/ml2024/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/aidml/miniconda3/envs/ml2024/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/aidml/miniconda3/envs/ml2024/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 310, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/aidml/miniconda3/envs/ml2024/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 306, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [16, 1, 3], expected input[128, 128, 72] to have 1 channels, but got 128 channels instead